### PR TITLE
[WIP]Kaminaripatch

### PR DESCRIPTION
**Pull request by koyamada314**
{What}
Insert-kaminari
&
Fix in kaminari-view to bootstrap do

{How}
gem-install
fix-view-file
generate-kaminari-view
ajust-kaminari-view

### CODE REVIEW

**Comment by Mochilefty** [comment]
LGTM!!!

**Comment by KazumaUede** [comment]
image

**Comment by polarizer45lc** [comment]
LGTM!

**Comment by fumiya0312** [comment]
image

**Pull request merged**
